// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_mimic_fasta
Rcpp::LogicalVector rcpp_mimic_fasta(std::string input_fasta_path, std::string output_fasta_path, unsigned int min_len, unsigned int num_shuffles, bool replace_i, unsigned int seed, std::string protein_name_prefix, double shared_peptide_ratio, bool prepend_original, bool infer_aa_frequency, bool verbose);
RcppExport SEXP _mimicR_rcpp_mimic_fasta(SEXP input_fasta_pathSEXP, SEXP output_fasta_pathSEXP, SEXP min_lenSEXP, SEXP num_shufflesSEXP, SEXP replace_iSEXP, SEXP seedSEXP, SEXP protein_name_prefixSEXP, SEXP shared_peptide_ratioSEXP, SEXP prepend_originalSEXP, SEXP infer_aa_frequencySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_fasta_path(input_fasta_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_fasta_path(output_fasta_pathSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_len(min_lenSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_shuffles(num_shufflesSEXP);
    Rcpp::traits::input_parameter< bool >::type replace_i(replace_iSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type protein_name_prefix(protein_name_prefixSEXP);
    Rcpp::traits::input_parameter< double >::type shared_peptide_ratio(shared_peptide_ratioSEXP);
    Rcpp::traits::input_parameter< bool >::type prepend_original(prepend_originalSEXP);
    Rcpp::traits::input_parameter< bool >::type infer_aa_frequency(infer_aa_frequencySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mimic_fasta(input_fasta_path, output_fasta_path, min_len, num_shuffles, replace_i, seed, protein_name_prefix, shared_peptide_ratio, prepend_original, infer_aa_frequency, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mimicR_rcpp_mimic_fasta", (DL_FUNC) &_mimicR_rcpp_mimic_fasta, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_mimicR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
