# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_mimic_fasta <- function(input_fasta_path, output_fasta_path, min_len = 0L, num_shuffles = 1L, replace_i = FALSE, seed = 0L, protein_name_prefix = "mimic|Random", shared_peptide_ratio = 0.0, prepend_original = FALSE, infer_aa_frequency = TRUE, verbose = FALSE) {
    .Call('_mimicR_rcpp_mimic_fasta', PACKAGE = 'mimicR', input_fasta_path, output_fasta_path, min_len, num_shuffles, replace_i, seed, protein_name_prefix, shared_peptide_ratio, prepend_original, infer_aa_frequency, verbose)
}
